Add error message indicating line number containing wrong section tit…
jr-packages/jrNotes pull request #32
Opened 2020-09-07 09:32 UTC by JohnMcIntyreJR

…le formatting

2020-09-09 20:57 UTC, csgillespie requested changes

2020-09-09 20:57 UTC, csgillespie commented on R/check_live.R
> +      line_numbers[pattern] = which(str_detect(r_code, pattern = error_strings[pattern]))
Why not have inside the for loop
```
if (!all(check)) {
    msg_error("Section should have the form: ## Section X.X: ", padding = 2)
    for (i in which(!check)) {
       line_number = which(str_detect(r_code, pattern = error_strings[i]))
       msg_error(paste("See line:", line_number), padding = 4)
    }
    set_error()
}
```
Also, you want to use `set_error()` as this will call the error at the end of the checks, so remove the `stop()` call. 

---

I think the above will work, but will need testing.

2020-09-15 16:26 UTC, JohnMcIntyreJR commented
@csgillespie Me and Rhian agreed for the test to be effective, the function should be split up. Hence why I have created a test for check_section_headers()

2020-09-21 09:10 UTC, csgillespie commented
@JohnMcIntyreJR You've committed a gitlab-ci file

2020-09-21 09:12 UTC, csgillespie requested changes
Delete .gitlab file and format news

2020-09-21 09:12 UTC, csgillespie commented on NEWS.md
>    * Feature: Add first test to jrNotes (check_section_headers())
The formatting for package names is `{jrNotes}`. For functions it's `check_section_headers()`.

2020-09-21 09:13 UTC, JohnMcIntyreJR commented
Yep was just in the process of deleting

2020-09-21 09:21 UTC, csgillespie commented on NEWS.md
> +  * Feature: Add first test to {jrNotes} (check_section_headers())
You need back ticks around `{jrNotes}` and around the function name for formatting

2020-09-21 09:22 UTC, csgillespie commented on NEWS.md
> +  * Feature: Error message with line number of section title with incorrect formatting
This is a bit unclear. What does it refer to?

2020-09-21 09:23 UTC, csgillespie commented on tests/testthat.R
> +library(jrNotes)
Put library calls in speech marks (JR notes style - library("jrNotes"))

2020-09-21 10:32 UTC, csgillespie commented
@JohnMcIntyreJR I've updated the test. The main role of the test should be to ensure that an error is (or isn't) raised. So ultimately that's what we'll need to check for.

2020-09-21 10:33 UTC, csgillespie approved these changes

2020-09-21 10:37 UTC, csgillespie requested changes
John, this change makes things more complicated. If I change something in `live/` I now get the feed back
```
ℹ Checking ../live/chapter2
  ℹ ../live/chapter2/master_tutor.R
  x Section should have the form: ## Section X.X: 
    x See line: 2
ℹ Chapter 2.1
  ℹ ## Section 2.1: A simple R session vs ## Section 2.1 A simple R session
```
This seems to duplicate information in a strange way.

2020-09-21 11:17 UTC, JohnMcIntyreJR commented
@csgillespie I see what you mean. The initial error message indicates line number then following note gives EXACTLY what the formatting should be. Both messages are useful but maybe not necessary.

I can remove the note comparing the correct and incorrect formatting? I prefer the error with the line number personally as I think it navigates you to the error quicker. Plus I think  "Section should have the form: ## Section X.X:" is clear. Thoughts?

2020-09-21 15:30 UTC, JohnMcIntyreJR commented on R/check_live.R
> +  for (i in chapters) {
Shouldn't this be seq_along(chapters)?

2020-09-21 15:31 UTC, JohnMcIntyreJR commented
@csgillespie I get this when I run check_live() in notes directory of Intro R:
◉ Checking live scripts formatting
ℹ Checking ../live/chapter2
  ℹ ../live/chapter2/master_tutor.R
 Error in if (expected_title != actual_title) { : 
  argument is of length zero

2020-09-21 17:40 UTC, csgillespie commented on R/check_live.R
> +  for (i in chapters) {
Yes, but it worked for me - very odd!

Changed and updated

2020-09-21 17:51 UTC, csgillespie commented
I can't reproduce this - very odd. Anyway I've updated the package.

> @csgillespie I get this when I run check_live() in notes directory of Intro R:
> ◉ Checking live scripts formatting
>  Checking ../live/chapter2
>  ../live/chapter2/master_tutor.R
> Error in if (expected_title != actual_title) { :
> argument is of length zero

2020-09-22 14:55 UTC, csgillespie approved these changes

2020-09-23 09:13 UTC, merged