'fix' clone_git_repo
jr-packages/jrNotes pull request #43
Opened 2020-09-15 16:21 UTC by jwalton3141

This is a work in progress.

`jrNotes::clone_git_repo()` has two issues to address:

- [ ] Clones cannot be pushed because they are shallow clones (created with the `--depth` argument)
- [ ] We no longer have `jumpingrivers-notes/course_notes`, which `clone_git_repo` uses to construct the remote url.

2020-09-15 16:27 UTC, jwalton3141 commented
@csgillespie @theoroe3 How should we approach the second issue?

> We no longer have `jumpingrivers-notes/course_notes`, which `clone_git_repo` uses to construct the remote url.

From what I can gather we used to have a single subgroup `jumpingrivers-notes/course_notes` which contained _all_ the course notes. 

_However_, we now have separate repos for python and R (https://gitlab.com/jumpingrivers-notes/python and https://gitlab.com/jumpingrivers-notes/r respectively).

The two possible solutions seem to be:
  1. Ask the user whether they're creating a python or R course and construct the remote url from this 
  2. Don't construct the remote url---this is left to the user to do manually

2020-09-15 16:31 UTC, theoroe3 commented
@jwalton3141 Aye it used to just be all groups in one (which was chaos looking back)

I think option 1 is good. Super easy to grab create the url after a user has given the name and specified R or Python

2020-09-15 16:32 UTC, theoroe3 requested changes
Add the "language" argument to the function and use it to create the repo url

2020-09-15 16:57 UTC, theoroe3 commented on R/clone_git_template.R
> +                        ".git")
glue should be `glue::glue("git@gitlab.com:jumpingrivers-notes/{language_path}/{name}.git")`

2020-09-17 14:09 UTC, theoroe3 approved these changes
Looks good

2020-09-17 14:09 UTC, merged